/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package miPrincipal;

public class Principal {

    public static void main(String[] args) {
        System.out.println("Factory App Assigment...");
    }
}
